os: Previous Windows Server 2012 R2

environment:
  matrix:
    - TARGET_ARCH: "x64"
      CONDA_PY: "27"
      CONDA_NPY: "19"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    - cmd: assoc .py
    - cmd: ftype Python.File
    - where python
    - cmd: assoc .py
    - cmd: ftype Python.File

# Skip .NET project specific build phase.
build: off

test_script:
    - cmd: assoc .py
    - cmd: ftype Python.File
    - hello.py

